"use client";import {useState} from "react";import {Menu,X,CheckCircle2,AlertCircle,Check,ShieldCheck,MessageSquare,FileText,TrendingUp,ArrowRight} from "lucide-react";import {services,audiences,faqs} from "@/data/content";import {ContactForm} from "./contact-form";import {site} from "@/config/site";
const nav=[["Kezdőlap","#kezdolap"],["Szolgáltatások","#szolgaltatasok"],["Csomagok","#csomagok"],["Kinek segítünk?","#kinek"],["Rólunk","#rolunk"],["Kapcsolat","#kapcsolat"]];
const CTA=({text="Kérek IT állapotfelmérést"}:{text?:string})=><a className="btn" href="#kapcsolat">{text}<ArrowRight size={17}/></a>;
export function Site(){const[menu,setMenu]=useState(false);return <><header><div className="container nav"><a className="logo" href="#kezdolap">NEXORA <b>IT</b></a><nav className="desktop">{nav.map(x=><a key={x[0]} href={x[1]}>{x[0]}</a>)}<CTA text="Ingyenes konzultáció"/></nav><button className="menubtn" aria-label="Menü" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>{menu&&<nav className="mobile">{nav.map(x=><a key={x[0]} href={x[1]} onClick={()=>setMenu(false)}>{x[0]}</a>)}</nav>}</div></header><main>
<section className="hero" id="kezdolap"><div className="container herogrid"><div><p className="eyebrow">Kiszámítható IT. Érthető támogatás.</p><h1>Megbízható informatikai háttér a vállalkozásod mögött.</h1><p className="lead">Rendszergazdai támogatás, szerverek, mentések, Microsoft 365, Linux és monitoring kis- és középvállalkozások számára.</p><div className="actions"><CTA/><a className="btn ghost" href="#szolgaltatasok">Szolgáltatások megtekintése</a></div><div className="trust">{["Üzleti nyelven","Prioritásokkal","Felesleges bonyolítás nélkül"].map(x=><span key={x}><CheckCircle2 size={17}/>{x}</span>)}</div></div><div className="dashboard"><div className="dashtop"><b>INFRASTRUCTURE OVERVIEW</b><em>● Élő állapot</em></div><div className="dashgrid">{[["SERVER STATUS","Online"],["BACKUP","Successful"],["MONITORING","All systems operational"],["SECURITY","Protected"],["UPTIME","99.9%"]].map(x=><div className="metric" key={x[0]}><small>{x[0]}</small><strong><i/> {x[1]}</strong></div>)}</div></div></div></section>
<section className="section"><div className="container"><Head over="Ismerős helyzetek?" title="Az informatika addig láthatatlan, amíg valami el nem romlik."/><div className="problems">{["Nincs saját rendszergazda","Nem tudni, működik-e a mentés","Elavult gépek és rendszerek","Microsoft 365 jogosultsági káosz","Lassú vagy instabil szerver","A hibák csak leálláskor derülnek ki"].map(x=><div key={x}><AlertCircle/>{x}</div>)}</div><p className="closing">Segítünk ezeket még azelőtt megtalálni és megoldani, hogy komolyabb problémát okoznának.</p></div></section>
<section className="section soft" id="szolgaltatasok"><div className="container"><Head over="Szolgáltatások" title="IT szolgáltatások, amikre egy KKV-nak valóban szüksége van."/><div className="cards">{services.map(({i:I,t,d})=><article className="card" key={t}><I/><h3>{t}</h3><p>{d}</p>{t==="IT állapotfelmérés"&&<a href="#kapcsolat">Állapotfelmérést kérek →</a>}</article>)}</div><div className="actions"><CTA/></div></div></section>
<section className="section"><div className="container audit"><div><p className="eyebrow">IT állapotfelmérés</p><h2>Nem tudod, milyen állapotban van a céged informatikája?</h2><p>Egy rövid felmérés során átnézzük a legfontosabb rendszereket, mentéseket, jogosultságokat és biztonsági kockázatokat, majd érthető prioritási listát kapsz.</p><CTA/></div><div className="checks">{["munkaállomások","hálózat","Microsoft 365","felhasználók és jogosultságok","vírusvédelem","mentések","szerverek","biztonsági kockázatok"].map(x=><span key={x}><Check/>{x}</span>)}</div></div></section>
<Pricing/><section className="section soft" id="kinek"><div className="container"><Head over="Célcsoportok" title="Kinek tudunk segíteni?"/><div className="cards">{audiences.map(({i:I,t,d})=><article className="card" key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section className="section"><div className="container"><Head over="Miért NEXORA IT?" title="Nem csak akkor foglalkozunk az IT-val, amikor már baj van."/><div className="benefits">{[[ShieldCheck,"Megelőzés","Monitoringgal, mentésellenőrzéssel és karbantartással időben felismerhetők a gondok."],[MessageSquare,"Érthető kommunikáció","A technikai problémákat üzleti nyelven is elmagyarázzuk."],[FileText,"Dokumentált rendszerek","Ne egyetlen ember fejében legyen minden beállítás és információ."],[TrendingUp,"Fokozatos fejlesztés","Először a legnagyobb kockázatokat kezeljük."]].map(([I,t,d])=>{const Icon=I as typeof ShieldCheck;return <article className="card" key={t as string}><Icon/><h3>{t as string}</h3><p>{d as string}</p></article>})}</div></div></section>
<section className="section soft"><div className="container"><Head over="Fejlődő infrastruktúra" title="Az alapoktól a modern infrastruktúráig." text="Nem feleslegesen bonyolult rendszereket építünk: az informatika a vállalkozásoddal együtt fejlődik."/><div className="road">{["IT Support","Server & Linux","Monitoring","Cloud & DevOps","Security","Automation & AI"].map(x=><span key={x}>{x} →</span>)}</div><h3>Technológiák, amelyekkel dolgozunk</h3><div className="tech">{["Microsoft 365","Linux","Docker","Kubernetes","Azure","Grafana","Prometheus","Git","VPN","Backup","Automation"].map(x=><span key={x}>{x}</span>)}</div></div></section>
<section className="section" id="rolunk"><div className="container about"><div><p className="eyebrow">Rólunk</p><h2>Személyes IT partner, üzleti szemlélettel.</h2><p>A NEXORA IT célja, hogy a kisebb vállalkozások is olyan átlátható és megbízható informatikai hátteret kapjanak, amely általában csak nagyobb cégeknél érhető el.</p></div><aside><b>Amire építünk</b><p>Rendszergazdai szemlélet, Linux és szerverüzemeltetés, monitoring, automatizálás, modern cloud/DevOps technológiák és folyamatos szakmai fejlődés.</p><p><strong>Nem technológiát adunk el.</strong> Azt adjuk, hogy az informatika működjön, az adatok biztonságban legyenek, és probléma esetén legyen kihez fordulni.</p></aside></div></section>
<section className="section soft"><div className="container faq"><Head over="Gyakori kérdések" title="Tisztázzuk a legfontosabbakat."/>{faqs.map(x=><details key={x[0]}><summary>{x[0]}</summary><p>{x[1]}</p></details>)}</div></section>
<section className="section" id="kapcsolat"><div className="container contact"><div><p className="eyebrow">Kapcsolat</p><h2>Nézzük meg, miben tudunk segíteni.</h2><p>Írd le röviden, milyen informatikai problémát szeretnél megoldani, és felvesszük veled a kapcsolatot.</p><small>Az űrlap jelenleg bemutató módban működik. API, Resend vagy CRM később könnyen csatlakoztatható.</small></div><ContactForm/></div></section></main><Footer/></>}
function Head({over,title,text}:{over:string,title:string,text?:string}){return <div className="head"><p className="eyebrow">{over}</p><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Pricing(){const plans=[{n:"Állapotfelmérés",p:"Egyedi ajánlat",l:["IT kockázatok felmérése","mentések ellenőrzése","biztonsági alapok","javaslati lista","prioritási sorrend"],c:"Ajánlatot kérek"},{n:"Havi IT Support",p:"Egyedi havidíj",l:["távoli segítség","felhasználói támogatás","rendszeres karbantartás","frissítések","mentések ellenőrzése","Microsoft 365 támogatás"],c:"Konzultációt kérek",f:true},{n:"Business Ops",p:"Projekt + havidíj",l:["szerverüzemeltetés","Linux","monitoring","VPN","jogosultságkezelés","biztonsági alapkontrollok","automatizálás"],c:"Beszéljük át"}];return <section className="section" id="csomagok"><div className="container"><Head over="Csomagok" title="Egyszerű, átlátható együttműködés."/><div className="cards pricing">{plans.map(x=><article className={`card price ${x.f?"featured":""}`} key={x.n}>{x.f&&<em>Legnépszerűbb</em>}<h3>{x.n}</h3><strong>{x.p}</strong><ul>{x.l.map(y=><li key={y}>✓ {y}</li>)}</ul><a className="btn ghost" href="#kapcsolat">{x.c}</a></article>)}</div><div className="actions"><CTA/></div></div></section>}
function Footer(){return <footer><div className="container foot"><div><a className="logo" href="#kezdolap">NEXORA <b>IT</b></a><p>{site.tagline}</p></div><div><strong>Oldaltérkép</strong>{[["Szolgáltatások","#szolgaltatasok"],["Csomagok","#csomagok"],["Kapcsolat","#kapcsolat"],["Adatkezelés","#"],["Impresszum", "#"]].map(x=><a key={x[0]} href={x[1]}>{x[0]}</a>)}</div><div><strong>Szolgáltatások</strong>{["IT támogatás","Linux / szerver","Mentések","Monitoring","Microsoft 365"].map(x=><a key={x} href="#szolgaltatasok">{x}</a>)}</div></div><div className="container copy">© 2026 {site.name}. Minden jog fenntartva.</div></footer>}
